# Etapa 1: Definir a imagem base do Node #
FROM node:20-alpine

# Etapa 2: Definir o diretório de trabalho do container #
WORKDIR /app

# Etapa 3: Copiar arquivos de dependência e instalar #
COPY package.json /.
COPY package-lock.json /.
# ou... COPY package*.json /. #

# instalando... 
RUN npm install 

# Etapa 4: Copiar o restante dos arquivos e compilar #
COPY . .

RUN npx prisma generate
RUN npm run build

# Etapa 5: Expor a porta da aplicação # 
EXPOSE 3000