services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: biancadb
      POSTGRES_PASSWORD: bianca-dev 
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"

  api: 
    build: 
      context: .
      dockerfile: dockerfile.api
    container_name: nest-api
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://biancadb:bianca-dev@postgres:5432/nestdb
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    command: sh -c "npx prisma migrate deploy && npm run start:prod"